In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
html_doc = requests.get('https://www.worldometers.info/coronavirus/')

In [3]:
soup = BeautifulSoup(html_doc.text, 'html')

In [4]:
table_content = soup.find('table')
table_head = table_content.find('thead')
table_body = table_content.find('tbody')
table_row = table_content.find_all('tr')
for data in table_row[8:]:
    # print(table_row)
    # print("---------------------------------------------------------------------------------------")
    pass

In [22]:
import csv
with open ("coronavirus_data.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    header_data = []
    for th in table_head.find_all('th'):
        header_data.append(th.text.strip());
    writer.writerow(header_data)
    
    for data in table_row[8:]:
        cells = data.find_all("td")

        row_data = [cell.text.strip() for cell in cells]
        writer.writerow(row_data)

print("Data successfully saved to coronavirus_data.csv!")

Data successfully saved to coronavirus_data.csv!

In [50]:
import pandas as pd

df = pd.read_csv("coronavirus_data.csv")
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,NaN,World,"704,753,890",0.0,"7,010,681",0.0,"675,619,811",790.0,"22,123,398","34,794",...,NaN,NaN,NaN,All,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,USA,"111,820,082",NaN,"1,219,487",NaN,"109,814,428",NaN,"786,167",940,...,"1,186,851,502","3,544,901","334,805,269",North America,3,275,0.0,NaN,NaN,"2,348"
2,2.0,India,"45,035,393",NaN,"533,570",NaN,NaN,NaN,NaN,NaN,...,"935,879,495","665,334","1,406,631,776",Asia,31,"2,636",2.0,NaN,NaN,0.4
3,3.0,France,"40,138,560",NaN,"167,642",NaN,"39,970,918",NaN,0,NaN,...,"271,490,188","4,139,547","65,584,518",Europe,2,391,0.0,NaN,NaN,NaN
4,4.0,Germany,"38,828,995",NaN,"183,027",NaN,"38,240,600",NaN,"405,368",NaN,...,"122,332,384","1,458,359","83,883,596",Europe,2,458,1.0,NaN,NaN,"4,833"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,NaN,Total:,"70,200,879",NaN,"1,367,332",NaN,"66,683,585",NaN,"2,149,962","8,953",...,NaN,NaN,NaN,South America,NaN,NaN,NaN,NaN,NaN,NaN
236,NaN,Total:,"14,895,771",NaN,"33,015",NaN,"14,752,388",NaN,"110,368",31,...,NaN,NaN,NaN,Australia/Oceania,NaN,NaN,NaN,NaN,NaN,NaN
237,NaN,Total:,"12,860,924",NaN,"258,892",NaN,"12,090,808",NaN,"511,224",529,...,NaN,NaN,NaN,Africa,NaN,NaN,NaN,NaN,NaN,NaN
238,NaN,Total:,721,NaN,15,NaN,706,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,NaN,Total:,"704,753,890",0.0,"7,010,681",0.0,"675,619,811",790.0,"22,123,398","34,794",...,NaN,NaN,NaN,All,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df["NewCases"]

0      0.0
1      NaN
2      NaN
3      NaN
4      NaN
      ...
235    NaN
236    NaN
237    NaN
238    NaN
239    0.0
Name: NewCases, Length: 240, dtype: float64

In [73]:
df["TotalCases"]

0      704,753,890
1      111,820,082
2       45,035,393
3       40,138,560
4       38,828,995
          ...
235     70,200,879
236     14,895,771
237     12,860,924
238            721
239    704,753,890
Name: TotalCases, Length: 240, dtype: object

In [79]:
df.loc[5, "TotalCases"]

'38,743,918'

In [94]:
df[df.ActiveCases=='0']

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
3,3.0,France,"40,138,560",NaN,"167,642",NaN,"39,970,918",NaN,0,NaN,...,"271,490,188","4,139,547","65,584,518",Europe,2,391,0.0,NaN,NaN,NaN
6,6.0,S. Korea,"34,571,873",NaN,"35,934",NaN,"34,535,939",NaN,0,NaN,...,"15,804,065","307,892","51,329,899",Asia,1,"1,428",3.0,NaN,NaN,NaN
9,9.0,UK,"24,910,387",NaN,"232,112",NaN,"24,678,275",NaN,0,NaN,...,"522,526,476","7,628,357","68,497,907",Europe,3,295,0.0,NaN,NaN,NaN
15,15.0,Taiwan,"10,241,523",NaN,"19,005",NaN,"10,222,518",NaN,0,NaN,...,"30,742,304","1,286,903","23,888,595",Asia,2,"1,257",1.0,NaN,NaN,NaN
26,26.0,Ukraine,"5,557,995",NaN,"112,418",NaN,"5,445,577",NaN,0,NaN,...,"32,603,805","754,855","43,192,122",Europe,8,384,1.0,NaN,NaN,NaN
32,32.0,DPRK,"4,772,813",NaN,74,NaN,"4,772,739",NaN,0,NaN,...,NaN,NaN,"25,990,679",Asia,5,"351,225",NaN,NaN,NaN,NaN
35,35.0,Peru,"4,572,667",NaN,"222,161",NaN,"4,350,506",NaN,0,4,...,"39,010,194","1,158,115","33,684,208",South America,7,152,1.0,NaN,NaN,NaN
40,40.0,Denmark,"3,183,756",NaN,"8,814",NaN,"3,174,942",NaN,0,NaN,...,"129,333,107","22,165,247","5,834,950",Europe,2,662,0.0,NaN,NaN,NaN
41,41.0,Singapore,"3,006,155",NaN,"2,024",NaN,"3,004,131",NaN,0,4,...,"24,756,666","4,165,302","5,943,546",Asia,2,"2,937",0.0,NaN,NaN,NaN
49,49.0,Slovakia,"1,877,605",NaN,"21,224",NaN,"1,856,381",NaN,0,23,...,"7,448,789","1,364,199","5,460,193",Europe,3,257,1.0,NaN,NaN,NaN
55,55.0,Norway,"1,509,732",NaN,"6,638",NaN,"1,503,094",NaN,0,NaN,...,"11,002,430","1,996,315","5,511,370",Europe,4,830,1.0,NaN,NaN,NaN
68,68.0,Ecuador,"1,070,188",NaN,"36,043",NaN,"1,034,145",NaN,0,NaN,...,"3,082,403","170,173","18,113,361",South America,17,503,6.0,NaN,NaN,NaN
72,72.0,Mongolia,"1,011,496",NaN,"2,284",NaN,"1,009,212",NaN,0,NaN,...,"4,030,048","1,193,000","3,378,078",Asia,3,"1,479",1.0,NaN,NaN,NaN
80,80.0,Cyprus,"681,110",NaN,"1,365",NaN,"679,745",NaN,0,NaN,...,"9,640,118","7,879,860","1,223,387",Asia,2,896,0.0,NaN,NaN,NaN
145,145.0,Sudan,"63,993",NaN,"5,046",NaN,"58,947",NaN,0,NaN,...,"562,941","12,240","45,992,020",Africa,719,"9,115",82.0,NaN,NaN,NaN
148,148.0,Syria,"57,743",NaN,"3,165",NaN,"54,578",NaN,0,NaN,...,"146,269","7,553","19,364,809",Asia,335,"6,118",132.0,NaN,NaN,NaN
150,150.0,Seychelles,"51,220",NaN,172,NaN,"51,048",NaN,0,NaN,...,NaN,NaN,"99,426",Africa,2,578,NaN,NaN,NaN,NaN
168,168.0,Saint Lucia,"30,215",NaN,410,NaN,"29,805",NaN,0,NaN,...,"210,983","1,139,752","185,113",North America,6,451,1.0,NaN,NaN,NaN
189,189.0,Marshall Islands,"16,138",NaN,17,NaN,"16,121",NaN,0,NaN,...,NaN,NaN,"60,057",Australia/Oceania,4,"3,533",NaN,NaN,NaN,NaN
190,190.0,Dominica,"16,038",NaN,74,NaN,"15,964",NaN,0,NaN,...,"229,344","3,170,187","72,344",North America,5,978,0.0,NaN,NaN,NaN
200,200.0,Eritrea,"10,189",NaN,103,NaN,"10,086",NaN,0,NaN,...,"23,693","6,470","3,662,244",Africa,359,"35,556",155.0,NaN,NaN,NaN
213,213.0,Saint Kitts and Nevis,"6,607",NaN,48,NaN,"6,559",NaN,0,NaN,...,"126,958","2,356,704","53,871",North America,8,"1,122",0.0,NaN,NaN,NaN
223,223.0,Falkland Islands,"1,930",NaN,NaN,NaN,"1,930",NaN,0,NaN,...,"8,632","2,439,107","3,539",South America,2,NaN,0.0,NaN,NaN,NaN
226,226.0,Diamond Princess,712,NaN,13,NaN,699,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,228.0,Vatican City,29,NaN,NaN,NaN,29,NaN,0,NaN,...,NaN,NaN,799,Europe,28,NaN,NaN,NaN,NaN,NaN
229,229.0,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,NaN,"626,161",Africa,"62,616","626,161",NaN,NaN,NaN,NaN
230,230.0,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238,NaN,Total:,721,NaN,15,NaN,706,NaN,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
df[df['Country,Other'] =='USA']

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,1.0,USA,"111,820,082",NaN,"1,219,487",NaN,"109,814,428",NaN,"786,167",940,...,"1,186,851,502","3,544,901","334,805,269",North America,3,275,0.0,NaN,NaN,"2,348"

In [112]:
country =['USA','UK']
df[df['Country,Other'].isin(country)]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,1.0,USA,"111,820,082",NaN,"1,219,487",NaN,"109,814,428",NaN,"786,167",940,...,"1,186,851,502","3,544,901","334,805,269",North America,3,275,0.0,NaN,NaN,"2,348"
9,9.0,UK,"24,910,387",NaN,"232,112",NaN,"24,678,275",NaN,0,NaN,...,"522,526,476","7,628,357","68,497,907",Europe,3,295,0.0,NaN,NaN,NaN

In [153]:
df[df['Country,Other'].str.contains ('U') & df['Country,Other'].str.contains ('A')]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,1.0,USA,"111,820,082",NaN,"1,219,487",NaN,"109,814,428",NaN,"786,167",940,...,"1,186,851,502","3,544,901","334,805,269",North America,3,275,0.0,NaN,NaN,"2,348"
69,69.0,UAE,"1,067,030",NaN,"2,349",NaN,NaN,NaN,NaN,NaN,...,"200,732,262","19,910,389","10,081,785",Asia,9,"4,292",0.0,NaN,NaN,"1,007"